#pragma once

#include <cstddef>
#include <cstdint>

#include "StreamingJsonParser.h"

// Streaming parser for the CrossInk release catalog served from GitHub Pages
// (docs/catalog, generated by scripts/generate_release_catalog.py):
//
//   { "schema_version": 1,
//     "releases": [ { "channel": "stable", "version": "1.4.0",
//                     "variant": "tiny", "firmware_url": "...",
//                     "firmware_sha256": "...", "size": 5491200, ... } ] }
//
// Picks the first release whose channel and variant match. The variant and
// channel strings must outlive the parser (pass string literals / constants).
class CatalogJsonParser {
 public:
  explicit CatalogJsonParser(const char* variant, const char* channel = "stable");

  CatalogJsonParser(const CatalogJsonParser&) = delete;
  CatalogJsonParser& operator=(const CatalogJsonParser&) = delete;

  void reset();
  void feed(const char* data, size_t len);

  bool foundRelease() const;
  const char* getVersion() const;
  const char* getFirmwareUrl() const;
  const char* getFirmwareSha256() const;
  size_t getFirmwareSize() const;

 private:
  enum class Position : uint8_t {
    TOP_LEVEL,
    IN_RELEASES_ARRAY,
    IN_RELEASE_OBJECT,
  };

  enum class LastKey : uint8_t {
    NONE,
    RELEASES,
    CHANNEL,
    VERSION,
    VARIANT,
    FIRMWARE_URL,
    FIRMWARE_SHA256,
    SIZE,
  };

  static void sOnKey(void* ctx, const char* key, size_t len);
  static void sOnString(void* ctx, const char* value, size_t len);
  static void sOnNumber(void* ctx, const char* value, size_t len);
  static void sOnBool(void* ctx, bool value);
  static void sOnNull(void* ctx);
  static void sOnObjectStart(void* ctx);
  static void sOnObjectEnd(void* ctx);
  static void sOnArrayStart(void* ctx);
  static void sOnArrayEnd(void* ctx);

  void commitRelease();

  StreamingJsonParser parser;
  const char* wantedVariant;
  const char* wantedChannel;

  Position position;
  LastKey lastKey;
  uint8_t depth;
  uint8_t releaseDepth;

  char version[32];
  char firmwareUrl[512];
  char firmwareSha256[65];
  size_t firmwareSize;
  bool releaseFound;

  char currentChannel[16];
  char currentVersion[32];
  char currentVariant[24];
  char currentUrl[512];
  char currentSha256[65];
  size_t currentSize;
};
